// The graph bank (src/shared/decision/graphBank.ts): every drawing is measured INDEPENDENTLY of the optimiser that produced it —
// vertex spacing, edges that cross, connectivity, and the clearance of every weight label and order badge.
//
// To re-bake the label positions after editing a graph:   BAKE_GRAPH_LABELS=1 npx vitest run src/tests/graphBank.test.ts -t bake

import { describe, expect, it } from "vitest";
import { GRAPH_BANK, bankCandidates, mirrored, sampleBankGraph } from "../shared/decision/graphBank";
import { crossingPairs, measureLabels, optimiseLabels } from "../shared/decision/graphBankLayout";
import { BANK_LABELS } from "../shared/decision/graphBankLabels.generated";

const GENERATED = new URL("../shared/decision/graphBankLabels.generated.ts", import.meta.url).pathname;
// (the app's tsconfig has no node types, so reach node through `any`)
const BAKE = !!(globalThis as any).process?.env?.BAKE_GRAPH_LABELS;

describe("bake", () => {
  it.skipIf(!BAKE)("bake the label positions", async () => {
    const { writeFileSync } = (await import("node:" + "fs")) as any;
    const out: Record<string, Record<string, number>> = {};
    for (const g of GRAPH_BANK) out[g.id] = optimiseLabels(g.nodes, g.edges);
    const body = Object.entries(out)
      .map(([id, m]) => `  ${JSON.stringify(id)}: { ${Object.entries(m).map(([e, t]) => `${e}: ${t}`).join(", ")} },`)
      .join("\n");
    writeFileSync(
      GENERATED,
      `// GENERATED by graphBank.test.ts (BAKE_GRAPH_LABELS=1) from the optimiser in graphBankLayout.ts — do not edit by hand.\n` +
        `// graph id → edge id → where the weight label sits, as a fraction along the edge (a → b).\n` +
        `export const BANK_LABELS: Record<string, Record<string, number>> = {\n${body}\n};\n`,
    );
  });
});

describe("the bank", () => {
  it("has the Network Flows shapes and the new ones, with unique ids", () => {
    const ids = GRAPH_BANK.map((g) => g.id);
    expect(new Set(ids).size).toBe(ids.length);
    expect(GRAPH_BANK.length).toBeGreaterThanOrEqual(24);
    for (const size of [4, 5, 6, 7, 8]) expect(bankCandidates({ size }).length, `graphs with ${size} vertices`).toBeGreaterThanOrEqual(size === 4 ? 2 : 3);
  });

  for (const g of GRAPH_BANK)
    describe(`${g.id} (${g.name}, ${g.size} vertices)`, () => {
      it("is well formed: lettered in reading order, edges reference vertices, ids alphabetical and unique", () => {
        expect(g.nodes.map((n) => n.id).join("")).toBe("ABCDEFGHIJ".slice(0, g.size));
        for (let i = 1; i < g.nodes.length; i++) expect(g.nodes[i].x).toBeGreaterThanOrEqual(g.nodes[i - 1].x);
        const ids = new Set(g.nodes.map((n) => n.id));
        const seen = new Set<string>();
        for (const e of g.edges) {
          expect(ids.has(e.a) && ids.has(e.b) && e.a < e.b, e.id).toBe(true);
          expect(e.id).toBe(e.a + e.b);
          expect(seen.has(e.id), `duplicate edge ${e.id}`).toBe(false);
          seen.add(e.id);
        }
      });

      it("keeps every vertex well apart", () => {
        for (let i = 0; i < g.nodes.length; i++)
          for (let j = i + 1; j < g.nodes.length; j++)
            expect(Math.hypot(g.nodes[i].x - g.nodes[j].x, g.nodes[i].y - g.nodes[j].y), `${g.nodes[i].id}–${g.nodes[j].id}`).toBeGreaterThanOrEqual(120);
      });

      // the new graphs guarantee it; the flow shapes (optional arcs there mean "present in some questions") rely on the sampler's own check
      it.skipIf(g.id.startsWith("flow-"))("is connected by its mandatory edges alone (so any subset of the optional ones is a connected network)", () => {
        const must = g.edges.filter((e) => !e.optional);
        const seen = new Set([g.nodes[0].id]);
        for (let grew = true; grew; ) {
          grew = false;
          for (const e of must) if (seen.has(e.a) !== seen.has(e.b)) { seen.add(e.a); seen.add(e.b); grew = true; }
        }
        expect(seen.size).toBe(g.size);
      });

      it("crosses only where declared (planar graphs not at all)", () => {
        const real = crossingPairs(g.nodes, g.edges).map((p) => p.join("|"));
        if (g.kind === "planar") expect(real).toEqual([]);
        else expect(g.crossings.map((p) => p.join("|")).sort()).toEqual(real.sort());
      });

      it("never passes an edge through a vertex that is not its own", () => {
        for (const e of g.edges) {
          const p = g.nodes.find((n) => n.id === e.a)!, q = g.nodes.find((n) => n.id === e.b)!;
          for (const n of g.nodes) {
            if (n.id === e.a || n.id === e.b) continue;
            const t = Math.max(0, Math.min(1, ((n.x - p.x) * (q.x - p.x) + (n.y - p.y) * (q.y - p.y)) / ((q.x - p.x) ** 2 + (q.y - p.y) ** 2)));
            expect(Math.hypot(n.x - (p.x + t * (q.x - p.x)), n.y - (p.y + t * (q.y - p.y))), `${e.id} past ${n.id}`).toBeGreaterThan(44);
          }
        }
      });

      it("has every weight label and order badge clear of vertices, other edges and each other (baked layout)", () => {
        expect(BANK_LABELS[g.id], "run the bake (see the top of this file)").toBeTruthy();
        const reports = measureLabels(g.nodes, g.edges, Object.fromEntries(g.edges.map((e) => [e.id, e.at])));
        for (const r of reports) {
          expect(r.at, `${r.id} position`).toBeGreaterThanOrEqual(0.15);
          expect(r.at).toBeLessThanOrEqual(0.85);
          expect(r.pill, `${g.id} ${r.id}: weight label clearance`).toBeGreaterThanOrEqual(3);
          expect(r.badge, `${g.id} ${r.id}: order badge clearance`).toBeGreaterThanOrEqual(0);
        }
      });
    });
});

describe("sampling", () => {
  it("mirroring keeps the drawing identical (same edges, same label positions on screen) and re-letters in reading order", () => {
    for (const g of GRAPH_BANK) {
      for (const [fx, fy] of [[true, false], [false, true], [true, true]] as const) {
        const m = mirrored(g, fx, fy);
        expect(m.nodes.map((n) => n.id).join("")).toBe("ABCDEFGHIJ".slice(0, g.size));
        expect(m.edges.length).toBe(g.edges.length);
        const reports = measureLabels(m.nodes, m.edges, Object.fromEntries(m.edges.map((e) => [e.id, e.at])));
        for (const r of reports) expect(r.pill, `${g.id} mirrored ${fx}/${fy} ${r.id}`).toBeGreaterThanOrEqual(3);
        expect(crossingPairs(m.nodes, m.edges).length).toBe(g.crossings.length);
      }
    }
  });

  it("sampled networks are connected, in range, lettered, with a label position on every edge", () => {
    for (let i = 0; i < 300; i++) {
      const size = 4 + (i % 5);
      const net = sampleBankGraph({ size, edges: [size, 3 * size] });
      expect(net.nodes.length).toBe(size);
      expect(net.edges.length).toBeGreaterThanOrEqual(size);
      for (const e of net.edges) expect(e.labelAt).toBeGreaterThan(0);
      const seen = new Set([net.nodes[0].id]);
      for (let grew = true; grew; ) {
        grew = false;
        for (const e of net.edges) if (seen.has(e.from) !== seen.has(e.to)) { seen.add(e.from); seen.add(e.to); grew = true; }
      }
      expect(seen.size).toBe(size);
    }
  });

  it("gives plenty of variety: many different drawings for each size", () => {
    for (const size of [5, 6, 7, 8]) {
      const seen = new Set<string>();
      for (let i = 0; i < 400; i++) {
        const n = sampleBankGraph({ size });
        seen.add(n.bankId + "|" + n.nodes.map((v) => v.x + "," + v.y).join(";") + "|" + n.edges.map((e) => e.id).join());
      }
      expect(seen.size, `distinct drawings with ${size} vertices`).toBeGreaterThan(40);
    }
  });
});
