// The graph bank (src/shared/decision/graphBank.ts): every drawing is measured INDEPENDENTLY of the optimiser that produced it —
// vertex spacing, edges that cross, connectivity, and the clearance of every weight label and order badge.
//
// To re-bake the label positions after editing a graph:   BAKE_GRAPH_LABELS=1 npx vitest run src/tests/graphBank.test.ts -t bake

import { describe, expect, it } from "vitest";
import { GRAPH_BANK, GRAPH_POLICY, bankCandidates, mirrored, sampleBankGraph, type BankUse } from "../shared/decision/graphBank";
import { crossingPairs, measureLabels, optimiseLabels } from "../shared/decision/graphBankLayout";
import { BANK_LABELS } from "../shared/decision/graphBankLabels.generated";

const GENERATED = new URL("../shared/decision/graphBankLabels.generated.ts", import.meta.url).pathname;
// (the app's tsconfig has no node types, so reach node through `any`)
const BAKE = !!(globalThis as any).process?.env?.BAKE_GRAPH_LABELS;

describe("bake", () => {
  it.skipIf(!BAKE)("bake the label positions", async () => {
    const { writeFileSync } = (await import("node:" + "fs")) as any;
    // every graph in each of its four orientations ("xy": 0 = as authored, 1 = mirrored), measured on the drawing as it will appear
    const out: Record<string, Record<string, Record<string, number>>> = {};
    for (const g of GRAPH_BANK) {
      out[g.id] = {};
      for (const [fx, fy] of [[0, 0], [1, 0], [0, 1], [1, 1]] as const) {
        const m = mirrored(g, fx === 1, fy === 1, false);
        out[g.id][`${fx}${fy}`] = optimiseLabels(m.nodes, m.edges);
      }
    }
    const body = Object.entries(out)
      .map(([id, v]) => `  ${JSON.stringify(id)}: {\n${Object.entries(v).map(([k, m]) => `    "${k}": { ${Object.entries(m).map(([e, t]) => `${e}: ${t}`).join(", ")} },`).join("\n")}\n  },`)
      .join("\n");
    writeFileSync(
      GENERATED,
      `// GENERATED by graphBank.test.ts (BAKE_GRAPH_LABELS=1) from the optimiser in graphBankLayout.ts — do not edit by hand.\n` +
        `// graph id → orientation ("xy": 00 as authored, 10 mirrored left↔right, 01 top↔bottom, 11 both) → edge id → where the weight label sits (fraction along the edge a → b).\n` +
        `export const BANK_LABELS: Record<string, Record<string, Record<string, number>>> = {\n${body}\n};\n`,
    );
  });
});

describe("the bank", () => {
  it("has the Network Flows shapes and the new ones, with unique ids", () => {
    const ids = GRAPH_BANK.map((g) => g.id);
    expect(new Set(ids).size).toBe(ids.length);
    expect(GRAPH_BANK.length).toBeGreaterThanOrEqual(24);
    for (const size of [4, 5, 6, 7, 8, 9, 10, 11, 12]) expect(bankCandidates({ size }).length, `graphs with ${size} vertices`).toBeGreaterThanOrEqual(size === 4 ? 2 : size >= 9 ? 1 : 3);
  });

  for (const g of GRAPH_BANK)
    describe(`${g.id} (${g.name}, ${g.size} vertices)`, () => {
      it("is well formed: lettered in reading order, edges reference vertices, ids alphabetical and unique", () => {
        expect(g.nodes.map((n) => n.id).join("")).toBe("ABCDEFGHIJKL".slice(0, g.size));
        for (let i = 1; i < g.nodes.length; i++) expect(g.nodes[i].x).toBeGreaterThanOrEqual(g.nodes[i - 1].x);
        const ids = new Set(g.nodes.map((n) => n.id));
        const seen = new Set<string>();
        for (const e of g.edges) {
          expect(ids.has(e.a) && ids.has(e.b) && e.a < e.b, e.id).toBe(true);
          expect(e.id).toBe(e.a + e.b);
          expect(seen.has(e.id), `duplicate edge ${e.id}`).toBe(false);
          seen.add(e.id);
        }
      });

      it("keeps every vertex well apart", () => {
        for (let i = 0; i < g.nodes.length; i++)
          for (let j = i + 1; j < g.nodes.length; j++)
            expect(Math.hypot(g.nodes[i].x - g.nodes[j].x, g.nodes[i].y - g.nodes[j].y), `${g.nodes[i].id}–${g.nodes[j].id}`).toBeGreaterThanOrEqual(120);
      });

      // the new graphs guarantee it; the flow shapes (optional arcs there mean "present in some questions") rely on the sampler's own check
      it.skipIf(g.id.startsWith("flow-"))("is connected by its mandatory edges alone (so any subset of the optional ones is a connected network)", () => {
        const must = g.edges.filter((e) => !e.optional);
        const seen = new Set([g.nodes[0].id]);
        for (let grew = true; grew; ) {
          grew = false;
          for (const e of must) if (seen.has(e.a) !== seen.has(e.b)) { seen.add(e.a); seen.add(e.b); grew = true; }
        }
        expect(seen.size).toBe(g.size);
      });

      it("crosses only where declared (planar graphs not at all)", () => {
        const real = crossingPairs(g.nodes, g.edges).map((p) => p.join("|"));
        if (g.kind === "planar") expect(real).toEqual([]);
        else expect(g.crossings.map((p) => p.join("|")).sort()).toEqual(real.sort());
      });

      it("never passes an edge through a vertex that is not its own", () => {
        for (const e of g.edges) {
          const p = g.nodes.find((n) => n.id === e.a)!, q = g.nodes.find((n) => n.id === e.b)!;
          for (const n of g.nodes) {
            if (n.id === e.a || n.id === e.b) continue;
            const t = Math.max(0, Math.min(1, ((n.x - p.x) * (q.x - p.x) + (n.y - p.y) * (q.y - p.y)) / ((q.x - p.x) ** 2 + (q.y - p.y) ** 2)));
            expect(Math.hypot(n.x - (p.x + t * (q.x - p.x)), n.y - (p.y + t * (q.y - p.y))), `${e.id} past ${n.id}`).toBeGreaterThan(44);
          }
        }
      });

      it("has every weight label and order badge clear of vertices, other edges and each other (baked layout)", () => {
        expect(BANK_LABELS[g.id]?.["11"], "run the bake (see the top of this file)").toBeTruthy();
        const reports = measureLabels(g.nodes, g.edges, Object.fromEntries(g.edges.map((e) => [e.id, e.at])));
        for (const r of reports) {
          expect(r.at, `${r.id} position`).toBeGreaterThanOrEqual(0.15);
          expect(r.at).toBeLessThanOrEqual(0.85);
          expect(r.pill, `${g.id} ${r.id}: weight label clearance`).toBeGreaterThanOrEqual(3);
          expect(r.badge, `${g.id} ${r.id}: order badge clearance`).toBeGreaterThanOrEqual(0);
        }
      });
    });
});

describe("which graph suits which tool (GRAPH_POLICY)", () => {
  const forUse = (u: BankUse) => GRAPH_BANK.filter((g) => g.uses.includes(u));
  it("every graph's tools follow the policy, and nothing outside it", () => {
    for (const g of GRAPH_BANK)
      for (const u of Object.keys(GRAPH_POLICY) as BankUse[]) expect(g.uses.includes(u), `${g.id} / ${u}`).toBe(GRAPH_POLICY[u].allows(g));
  });
  it("Minimum Spanning Tree: planar graphs only, 5–12 vertices, with large ones available (9, 10, 11 and 12 vertices)", () => {
    const mst = forUse("mst");
    expect(mst.every((g) => g.kind === "planar" && g.size >= 5 && g.size <= 12)).toBe(true);
    for (const n of [5, 6, 7, 8]) expect(mst.filter((g) => g.size === n).length, `${n} vertices`).toBeGreaterThanOrEqual(3);
    for (const n of [9, 10]) expect(mst.filter((g) => g.size === n).length, `${n} vertices`).toBeGreaterThanOrEqual(2);
    for (const n of [11, 12]) expect(mst.filter((g) => g.size === n).length, `${n} vertices`).toBeGreaterThanOrEqual(1);
  });
  it("Travelling Salesperson: only the complete graphs K4–K6, and sparse planar graphs of at most 6 vertices — never a large graph", () => {
    expect(forUse("tspComplete").map((g) => g.id).sort()).toEqual(["k4", "k5", "k6"]);
    const practical = forUse("tspPractical");
    expect(practical.every((g) => g.size <= 6 && g.kind === "planar")).toBe(true);
    for (const n of [5, 6]) expect(practical.filter((g) => g.size === n).length, `${n} vertices`).toBeGreaterThanOrEqual(3);
    expect(practical.filter((g) => g.size === 4).length).toBeGreaterThanOrEqual(1);
  });
  it("large graphs (more than 8 vertices) are for spanning trees and the sandbox only", () => {
    for (const g of GRAPH_BANK.filter((x) => x.size > 8)) expect(g.uses.sort()).toEqual(["mst", "sandbox"]);
  });
  it("sampling for a tool never returns a graph outside its policy", () => {
    for (const u of ["mst", "tspPractical", "tspComplete"] as BankUse[])
      for (let i = 0; i < 100; i++) {
        const net = sampleBankGraph({ use: u, ...(u === "tspComplete" ? { ids: ["k5"] } : {}) });
        expect(GRAPH_BANK.find((g) => g.id === net.bankId)!.uses).toContain(u);
      }
  });
});

describe("sampling", () => {
  it("mirroring keeps the drawing identical (same edges, same label positions on screen) and re-letters in reading order", () => {
    for (const g of GRAPH_BANK) {
      for (const [fx, fy] of [[true, false], [false, true], [true, true]] as const) {
        const m = mirrored(g, fx, fy);
        expect(m.nodes.map((n) => n.id).join("")).toBe("ABCDEFGHIJKL".slice(0, g.size));
        expect(m.edges.length).toBe(g.edges.length);
        const reports = measureLabels(m.nodes, m.edges, Object.fromEntries(m.edges.map((e) => [e.id, e.at])));
        for (const r of reports) expect(r.pill, `${g.id} mirrored ${fx}/${fy} ${r.id}`).toBeGreaterThanOrEqual(3);
        expect(crossingPairs(m.nodes, m.edges).length).toBe(g.crossings.length);
      }
    }
  });

  it("sampled networks are connected, in range, lettered, with a label position on every edge", () => {
    for (let i = 0; i < 300; i++) {
      const size = 4 + (i % 9);
      const net = sampleBankGraph({ size, edges: [size, 3 * size] });
      expect(net.nodes.length).toBe(size);
      expect(net.edges.length).toBeGreaterThanOrEqual(size);
      for (const e of net.edges) expect(e.labelAt).toBeGreaterThan(0);
      const seen = new Set([net.nodes[0].id]);
      for (let grew = true; grew; ) {
        grew = false;
        for (const e of net.edges) if (seen.has(e.from) !== seen.has(e.to)) { seen.add(e.from); seen.add(e.to); grew = true; }
      }
      expect(seen.size).toBe(size);
    }
  });

  it("gives plenty of variety: many different drawings for each size", () => {
    for (const size of [5, 6, 7, 8]) {
      const seen = new Set<string>();
      for (let i = 0; i < 400; i++) {
        const n = sampleBankGraph({ size });
        seen.add(n.bankId + "|" + n.nodes.map((v) => v.x + "," + v.y).join(";") + "|" + n.edges.map((e) => e.id).join());
      }
      expect(seen.size, `distinct drawings with ${size} vertices`).toBeGreaterThan(40);
    }
  });
});
