// Depth bank for Rounding — fixed, hand-written questions (see src/shared/depth.ts and specs/depth/rounding.md).
// Levels follow the IDEAS, not the tool's number-line presentation levels:
//   1  Which way?            the two neighbours, the halfway value, the number line
//   2  Which digit decides?  rounding digit + decider; "round the digit but keep the rest"; trailing zeros
//   3  Edge cases & accuracy  carrying over 9s, leading zeros, double rounding, the range that rounds to a value
// Items with no `tool` show on every tab; tab-specific ones name `tool` and the pool option they use as `needs`.
// Every numeric claim below is asserted in src/tests/roundingDepth.test.ts.

import type { DepthItem, DepthVisual } from "../../shared/depth";
import { depthLine, type DepthLineSpec } from "./RoundingDepthLine";

// The number line is a scaffold: the teacher switches it on, and separately the plotted point, from the slide's side rail
// (both off to begin with — a plotted line can give the answer away).
const line = (spec: DepthLineSpec): DepthVisual => ({
  type: "custom", labels: { show: "Number line", plot: "Plot the point" },
  render: (onAnswer, plot) => depthLine(spec, onAnswer, plot),
});

// One number line per item — every item, on every level and sub-tool, offers the same scaffold (see `line`). Each line
// is drawn in the item's own units (d.p. items in decimals, s.f. items in significant-figure steps) and is checked
// against the item's numbers in src/tests/roundingDepth.test.ts. `ring` / `shade` / `midLabel` are only set where the
// question is not "which end is it nearer to?" (the range items: the middle is the answer, and the whole span rounds to it).
export const ITEM_LINES: Record<string, DepthLineSpec> = {
  // Level 1
  "rnd-leo-mia": { lo: "40", mid: "45", hi: "50", num: "47", pos: 0.7 },
  "rnd-two-neighbours": { lo: "3,400", mid: "3,450", hi: "3,500", num: "3,482", pos: 0.82 },
  "rnd-halfway": { lo: "300", mid: "350", hi: "400", num: "350", pos: 0.5 },
  "rnd-explain-down": { lo: "80", mid: "85", hi: "90", num: "86", pos: 0.6 },
  "rnd-explain-already": { lo: "340", mid: "345", hi: "350", num: "340", pos: 0 },
  "rnd-extend-asn": { lo: "40", mid: "45", hi: "50", num: "43", pos: 0.3 },
  "rnd-extend-range-50": { lo: "450", mid: "500", hi: "550", num: "500", pos: 0.5, ring: "mid", shade: "all", midLabel: "rounds to" },
  // Level 2
  "rnd-keep-rest": { lo: "30", mid: "35", hi: "40", num: "31.04", pos: 0.104 },
  "rnd-digit-nearest": { lo: "3,400", mid: "3,450", hi: "3,500", num: "3,482", pos: 0.82 },
  "rnd-digit-dp": { lo: "6.73", mid: "6.735", hi: "6.74", num: "6.738", pos: 0.8 },
  "rnd-cutoff": { lo: "2.67", mid: "2.675", hi: "2.68", num: "2.678", pos: 0.8 },
  "rnd-chain": { lo: "3,000", mid: "3,500", hi: "4,000", num: "3,462", pos: 0.462 },
  "rnd-explain-priya": { lo: "400", mid: "450", hi: "500", num: "482.6", pos: 0.826 },
  "rnd-explain-trail": { lo: "4.29", mid: "4.295", hi: "4.30", num: "4.296", pos: 0.6 },
  "rnd-extend-zero": { lo: "40", mid: "45", hi: "50", num: "47.3", pos: 0.73 },
  "rnd-extend-many": { lo: "65", mid: "70", hi: "75", num: "70", pos: 0.5, ring: "mid", shade: "all", midLabel: "rounds to" },
  // Level 3
  "rnd-nines": { lo: "390", mid: "395", hi: "400", num: "396", pos: 0.6 },
  "rnd-zero-sf": { lo: "0.0047", mid: "0.00475", hi: "0.0048", num: "0.00472", pos: 0.2 },
  "rnd-placeholder-sf": { lo: "4,700", mid: "4,750", hi: "4,800", num: "4,726", pos: 0.26 },
  "rnd-nine-dp": { lo: "0.09", mid: "0.095", hi: "0.10", num: "0.0996", pos: 0.96 },
  "rnd-explain-double": { lo: "2", mid: "2.5", hi: "3", num: "2.46", pos: 0.46 },
  "rnd-explain-zoe": { lo: "0.038", mid: "0.0385", hi: "0.039", num: "0.0384", pos: 0.4 },
  "rnd-extend-range-dp": { lo: "2.35", mid: "2.4", hi: "2.45", num: "2.4", pos: 0.5, ring: "mid", shade: "all", midLabel: "rounds to" },
  "rnd-extend-sfdp": { lo: "0", mid: "0.005", hi: "0.01", num: "0.00472", pos: 0.472 },
  "rnd-extend-convince": { lo: "2.99", mid: "2.995", hi: "3.00", num: "2.995", pos: 0.5 },
  // Added so every sub-tool keeps diagnose, explain and extend at each level
  "rnd-explain-middle": { lo: "4,490", mid: "4,495", hi: "4,500", num: "4,495", pos: 0.5 },
  "rnd-extend-range-10": { lo: "6,995", mid: "7,000", hi: "7,005", num: "7,000", pos: 0.5, ring: "mid", shade: "all", midLabel: "rounds to" },
  "rnd-dp1-who": { lo: "3.4", mid: "3.45", hi: "3.5", num: "3.46", pos: 0.6 },
  "rnd-dp1-explain": { lo: "5.3", mid: "5.35", hi: "5.4", num: "5.38", pos: 0.8 },
  "rnd-dp1-always": { lo: "6.0", mid: "6.05", hi: "6.1", num: "6.04", pos: 0.4 },
  "rnd-dp-how-many": { lo: "3.65", mid: "3.70", hi: "3.75", num: "3.70", pos: 0.5, ring: "mid", shade: "all", midLabel: "rounds to" },
  "rnd-dp1-from-end": { lo: "8.2", mid: "8.25", hi: "8.3", num: "8.249", pos: 0.49 },
  "rnd-dp1-zero": { lo: "27.4", mid: "27.45", hi: "27.5", num: "27.46", pos: 0.6 },
  "rnd-dp1-carry": { lo: "0.9", mid: "0.95", hi: "1.0", num: "0.96", pos: 0.6 },
  "rnd-sf1-carry": { lo: "9,000", mid: "9,500", hi: "10,000", num: "9,640", pos: 0.64 },
  "rnd-sf1-zeros": { lo: "0.004", mid: "0.0045", hi: "0.005", num: "0.00472", pos: 0.72 },
  "rnd-sf1-which": { lo: "4,000", mid: "4,500", hi: "5,000", num: "4,726", pos: 0.726 },
  "rnd-sf1-explain": { lo: "300", mid: "350", hi: "400", num: "326", pos: 0.26 },
  "rnd-sf1-always": { lo: "90", mid: "95", hi: "100", num: "96", pos: 0.6 },
  "rnd-sf2-lead": { lo: "0.038", mid: "0.0385", hi: "0.039", num: "0.0384", pos: 0.4 },
  "rnd-sf2-explain": { lo: "8,400", mid: "8,450", hi: "8,500", num: "8,462", pos: 0.62 },
  "rnd-sf2-range": { lo: "3,350", mid: "3,400", hi: "3,450", num: "3,400", pos: 0.5, ring: "mid", shade: "all", midLabel: "rounds to" },
};

export const DEPTH_ITEMS: DepthItem[] = [
  // ───────────────────────── Level 1 — Which way? ─────────────────────────
  {
    id: "rnd-leo-mia", level: "level1", tool: "nearest", purpose: "diagnose", startHere: true,
    title: "Who is right?",
    speakers: [
      { name: "Mei", says: ["$47$ to the nearest $10$ is $40$ — the tens digit is $4$."] },
      { name: "Ben", says: ["$47$ to the nearest $10$ is $50$ — it is closer to $50$."] },
    ],
    visual: line(ITEM_LINES["rnd-leo-mia"]),
    question: ["Who is right?"],
    options: [
      { text: "Mei", misconception: "Reads the tens digit and stops — never looks at how far through the interval the number is" },
      { text: "Ben", correct: true },
      { text: "They are both right", misconception: "Thinks either neighbour is an acceptable answer" },
    ],
    answer: [
      "Ben is right: $47$ lies between $40$ and $50$.",
      "Halfway is $45$, and $47$ is past it, so it is closer to $50$.",
      "Mei stopped at the $4$ in the tens place — rounding means choosing the nearer of the two neighbours.",
    ],
    teacherNote: "Ask where Mei's 40 came from. Listen for 'the tens digit stays the same' — that is the habit to break.",
    ifNotSecure: "rnd-explain-down", ifSecure: "rnd-halfway",
  },
  {
    id: "rnd-two-neighbours", level: "level1", tool: "nearest", needs: ["n100"], purpose: "diagnose",
    title: "The two neighbours",
    visual: line(ITEM_LINES["rnd-two-neighbours"]),
    question: ["$3{,}482$ is going to be rounded to the nearest $100$.", "Which two numbers is it between?"],
    options: [
      { text: "$3{,}400$ and $3{,}500$", correct: true },
      { text: "$3{,}480$ and $3{,}490$", misconception: "Uses the neighbours for the nearest 10, not the nearest 100" },
      { text: "$3{,}000$ and $4{,}000$", misconception: "Uses the neighbours for the nearest 1000, not the nearest 100" },
    ],
    answer: [
      "The nearest $100$ means the neighbours are multiples of $100$: $3{,}400$ and $3{,}500$.",
      "Halfway is $3{,}450$; $3{,}482$ is past it, so it rounds to $3{,}500$.",
    ],
    teacherNote: "Make the link explicit: the thing you round to decides the neighbours.",
    ifNotSecure: "rnd-leo-mia", ifSecure: "rnd-halfway",
  },
  {
    id: "rnd-halfway", level: "level1", tool: "nearest", purpose: "diagnose",
    title: "Exactly in the middle",
    visual: line(ITEM_LINES["rnd-halfway"]),
    question: ["Round $350$ to the nearest $100$."],
    options: [
      { text: "$300$", misconception: "Thinks a number exactly halfway has not gone 'past' halfway, so it stays down" },
      { text: "$400$", correct: true },
      { text: "$350$", misconception: "Thinks a number that is already 'nice' does not need rounding" },
    ],
    answer: [
      "$350$ is exactly halfway between $300$ and $400$.",
      "By convention a number exactly halfway rounds up, so $350 \\to 400$.",
      "This is the same as the digit rule: the decider is $5$, and $5$ or more rounds up.",
    ],
    teacherNote: "It is a convention, not a discovery — say so. Ask what the digit rule says.",
    ifNotSecure: "rnd-leo-mia", ifSecure: "rnd-extend-range-50",
  },
  {
    id: "rnd-explain-down", level: "level1", tool: "nearest", purpose: "explain",
    title: "Explain this mistake",
    speakers: [{ name: "Amara", says: ["$86$ to the nearest $10$ is $80$, because I look at the $8$ and keep it."] }],
    visual: line(ITEM_LINES["rnd-explain-down"]),
    question: ["Explain what Amara has done wrong. What should the answer be?"],
    answer: [
      "Amara kept the tens digit and ignored the units.",
      "$86$ is between $80$ and $90$. Halfway is $85$, and $86$ is past it.",
      "So $86$ is closer to $90$: $86 \\to 90$.",
    ],
    teacherNote: "Listen for 'they didn't check which end it is closer to'. Draw the line if they struggle.",
    ifNotSecure: "rnd-leo-mia", ifSecure: "rnd-halfway",
  },
  {
    id: "rnd-explain-already", level: "level1", tool: "nearest", purpose: "explain",
    title: "Nothing to do?",
    speakers: [{ name: "Priya", says: ["I rounded $340$ to the nearest $10$ and it did not change — I must have done it wrong."] }],
    visual: line(ITEM_LINES["rnd-explain-already"]),
    question: ["Is Priya right to worry? Explain."],
    answer: [
      "Priya is not wrong: $340$ is already a multiple of $10$.",
      "It is one of the two neighbours, so it rounds to itself: $340 \\to 340$.",
      "A number that is already on a mark does not move.",
    ],
    teacherNote: "Link to the line: the number sits exactly on an end. Ask for another number that would not change.",
    ifNotSecure: "rnd-leo-mia", ifSecure: "rnd-extend-many",
  },
  {
    id: "rnd-extend-asn", level: "level1", tool: "nearest", purpose: "extend",
    title: "Always, sometimes, never",
    visual: line(ITEM_LINES["rnd-extend-asn"]),
    question: ["A number rounded to the nearest $10$ is bigger than the original number.", "Always, sometimes or never? Give examples."],
    answer: [
      "Sometimes.",
      "Bigger: $47 \\to 50$. Smaller: $43 \\to 40$. The same: $40 \\to 40$.",
      "Rounding up makes it bigger, rounding down makes it smaller, and a number on a mark does not change.",
    ],
    teacherNote: "Push for all three cases. Ask what makes a number round up rather than down.",
    ifNotSecure: "rnd-leo-mia", ifSecure: "rnd-extend-range-50",
  },
  {
    id: "rnd-extend-range-50", level: "level1", tool: "nearest", purpose: "extend",
    title: "Smallest and largest",
    visual: line(ITEM_LINES["rnd-extend-range-50"]),
    question: ["A whole number is rounded to the nearest $100$ and the answer is $500$.", "What is the smallest it could be? What is the largest?"],
    answer: [
      "Smallest: $450$ (halfway rounds up, so $450 \\to 500$).",
      "Largest: $549$ ($550$ would round up to $600$).",
      "So every whole number from $450$ to $549$ rounds to $500$ — that is $100$ numbers.",
    ],
    teacherNote: "Many will say 449 or 550. Use the line: where does the 'round to 500' region start and stop?",
    ifNotSecure: "rnd-halfway", ifSecure: "rnd-extend-range-dp",
  },

  // ───────────────────────── Level 2 — Which digit decides? ─────────────────────────
  {
    id: "rnd-keep-rest", level: "level2", tool: "nearest", purpose: "diagnose", startHere: true,
    title: "Who is right?",
    speakers: [
      { name: "Ruby", says: ["$31.04$ to the nearest $10$ is $30.04$."] },
      { name: "Kofi", says: ["$31.04$ to the nearest $10$ is $30$."] },
    ],
    visual: line(ITEM_LINES["rnd-keep-rest"]),
    question: ["Who is right?"],
    options: [
      { text: "Ruby", misconception: "Rounds the digit but keeps everything else — the decimal part is carried along untouched" },
      { text: "Kofi", correct: true },
      { text: "They are both right", misconception: "Thinks the decimal part may stay if it is small" },
    ],
    answer: [
      "Kofi is right: $31.04$ is between $30$ and $40$, and below halfway ($35$), so it rounds to $30$.",
      "Rounding to the nearest $10$ means the answer is a multiple of $10$ — $30.04$ is not one.",
      "Everything after the rounding digit is dropped (or replaced by zeros), never kept.",
    ],
    teacherNote: "Common when decimals meet whole-number rounding. Ask: 'Is 30.04 a multiple of 10?'",
    ifNotSecure: "rnd-explain-down", ifSecure: "rnd-explain-priya",
  },
  {
    id: "rnd-digit-nearest", level: "level2", tool: "nearest", needs: ["n100"], purpose: "diagnose",
    title: "Which digit decides?",
    visual: line(ITEM_LINES["rnd-digit-nearest"]),
    question: ["Round $3{,}482$ to the nearest $100$.", "Which digit decides whether to round up or down?"],
    options: [
      { text: "$3$", misconception: "Looks at the first digit instead of the one after the rounding digit" },
      { text: "$4$", misconception: "Confuses the rounding digit (the one being rounded) with the decider" },
      { text: "$8$", correct: true },
      { text: "$2$", misconception: "Looks at the last digit" },
    ],
    answer: [
      "The rounding digit is the hundreds digit, $4$. The decider is the digit right after it: $8$.",
      "$8$ is $5$ or more, so round up: $3{,}482 \\to 3{,}500$.",
    ],
    teacherNote: "Have them name the rounding digit first, then the decider — two different digits.",
    ifNotSecure: "rnd-two-neighbours", ifSecure: "rnd-chain",
  },
  {
    id: "rnd-digit-dp", level: "level2", tool: "dp", needs: ["dp2"], purpose: "diagnose",
    title: "Which digit decides?",
    visual: line(ITEM_LINES["rnd-digit-dp"]),
    question: ["Round $6.738$ to $2$ decimal places.", "Which digit decides whether to round up or down?"],
    options: [
      { text: "$7$", misconception: "Looks at the first decimal digit instead of the one after the rounding digit" },
      { text: "$3$", misconception: "Confuses the rounding digit (the last one kept) with the decider" },
      { text: "$8$", correct: true },
      { text: "$6$", misconception: "Looks at the whole-number digit" },
    ],
    answer: [
      "$2$ d.p. means keeping two digits after the point: the rounding digit is $3$. The decider is the next digit: $8$.",
      "$8$ is $5$ or more, so round up: $6.738 \\to 6.74$.",
    ],
    teacherNote: "Have them draw the dotted line after the last digit they keep.",
    ifNotSecure: "rnd-keep-rest", ifSecure: "rnd-explain-trail",
  },
  {
    id: "rnd-cutoff", level: "level2", tool: "dp", needs: ["dp2"], purpose: "diagnose",
    title: "Round or cut off?",
    visual: line(ITEM_LINES["rnd-cutoff"]),
    question: ["Round $2.678$ to $2$ decimal places."],
    options: [
      { text: "$2.67$", misconception: "Chops the number off after two decimal places without looking at the decider" },
      { text: "$2.68$", correct: true },
      { text: "$2.7$", misconception: "Rounds to 1 decimal place instead of 2" },
    ],
    answer: [
      "The rounding digit is $7$ and the decider is $8$, which is $5$ or more, so round up.",
      "$2.678 \\to 2.68$.",
      "Chopping off after two decimal places gives $2.67$ — that is truncating, not rounding.",
    ],
    teacherNote: "Ask them to put 2.67 and 2.68 on a line and place 2.678 — which is it nearer?",
    ifNotSecure: "rnd-digit-dp", ifSecure: "rnd-explain-trail",
  },
  {
    id: "rnd-chain", level: "level2", tool: "nearest", needs: ["n1000"], purpose: "explain",
    title: "Round, round, round",
    speakers: [{ name: "Leo", says: ["$3{,}462$ to the nearest $1000$: first to the nearest $10$ is $3{,}460$, then to the nearest $100$ is $3{,}500$, then to the nearest $1000$ is $4{,}000$."] }],
    visual: line(ITEM_LINES["rnd-chain"]),
    question: ["Is Leo's answer right? Explain what she did."],
    answer: [
      "Leo's answer, $4{,}000$, is wrong. $3{,}462$ rounds to $3{,}000$.",
      "Rounding in stages is the mistake: each rounding built on the last one.",
      "Only the decider matters: the hundreds digit is $4$, which is less than $5$, so round down once.",
    ],
    teacherNote: "Draw 3000 — 3500 — 4000 and mark 3462. It never gets past the halfway mark.",
    ifNotSecure: "rnd-digit-nearest", ifSecure: "rnd-explain-double",
  },
  {
    id: "rnd-explain-priya", level: "level2", tool: "nearest", purpose: "explain",
    title: "Explain this mistake",
    speakers: [{ name: "Leo", says: ["$482.6$ to the nearest $100$ is $500.6$."] }],
    visual: line(ITEM_LINES["rnd-explain-priya"]),
    question: ["Explain what Leo has done. What should the answer be?"],
    answer: [
      "Leo rounded the hundreds digit but kept the rest of the number.",
      "The decider is $8$, so round up to $500$ — and everything after the rounding digit is dropped.",
      "$482.6 \\to 500$. The answer is a multiple of $100$, not $500.6$.",
    ],
    teacherNote: "Same misconception as Ruby and Kofi, one step further out. Ask what the answer should look like.",
    ifNotSecure: "rnd-keep-rest", ifSecure: "rnd-extend-zero",
  },
  {
    id: "rnd-explain-trail", level: "level2", tool: "dp", needs: ["dp2"], purpose: "explain",
    title: "The missing zero",
    speakers: [{ name: "Amara", says: ["$4.296$ to $2$ d.p. is $4.3$."] }],
    visual: line(ITEM_LINES["rnd-explain-trail"]),
    question: ["Is Amara right? Explain."],
    answer: [
      "Amara has the right value but not the right accuracy.",
      "$4.296 \\to 4.30$: the rounding digit $9$ goes up to $10$, which carries into the tenths.",
      "The final zero stays — it shows the answer is accurate to $2$ decimal places. $4.3$ only shows $1$.",
    ],
    teacherNote: "Ask what the 0 is telling the reader. Link to money: £4.3 is not how we write £4.30.",
    ifNotSecure: "rnd-cutoff", ifSecure: "rnd-extend-convince",
  },
  {
    id: "rnd-extend-zero", level: "level2", tool: "nearest", purpose: "extend",
    title: "Always, sometimes, never",
    visual: line(ITEM_LINES["rnd-extend-zero"]),
    question: ["A number rounded to the nearest $10$ always ends in $0$.", "Always, sometimes or never? What about $47.3$?"],
    answer: [
      "Always.",
      "The answer is a multiple of $10$, so its last digit (units) is $0$.",
      "$47.3 \\to 50$, not $50.3$ — the decimal part does not survive rounding to the nearest $10$.",
    ],
    teacherNote: "Connect back to Ruby's 30.04: a multiple of 10 cannot have a decimal part.",
    ifNotSecure: "rnd-keep-rest", ifSecure: "rnd-extend-range-dp",
  },
  {
    id: "rnd-extend-many", level: "level2", tool: "nearest", purpose: "extend",
    title: "How many?",
    visual: line(ITEM_LINES["rnd-extend-many"]),
    question: ["How many whole numbers round to $70$ when rounded to the nearest $10$?", "What if the numbers can have one decimal place?"],
    answer: [
      "Whole numbers: $65, 66, \\dots, 74$ — that is $10$ numbers ($65$ rounds up, $75$ rounds to $80$).",
      "With one decimal place: from $65.0$ up to $74.9$ — that is $100$ numbers.",
      "In general, the numbers that round to $70$ form an interval, not a list.",
    ],
    teacherNote: "Look for 'there are two ends of the interval' and whether they include or exclude the ends.",
    ifNotSecure: "rnd-explain-already", ifSecure: "rnd-extend-range-dp",
  },

  // ───────────────────────── Level 3 — Edge cases & accuracy ─────────────────────────
  {
    id: "rnd-nines", level: "level3", tool: "nearest", purpose: "diagnose", startHere: true,
    title: "Carrying over",
    visual: line(ITEM_LINES["rnd-nines"]),
    question: ["Round $396$ to the nearest $10$."],
    options: [
      { text: "$390$", misconception: "Cuts off after the tens digit without looking at the decider" },
      { text: "$3{,}100$", misconception: "Adds 1 to the 9 and writes '10' in the tens place without carrying" },
      { text: "$400$", correct: true },
    ],
    answer: [
      "The rounding digit is $9$ and the decider is $6$, so round up.",
      "$9 + 1 = 10$, so the $10$ carries into the hundreds: $396 \\to 400$.",
      "$396$ is $4$ away from $400$ but $6$ away from $390$.",
    ],
    teacherNote: "Draw the line 390 — 400. Rounding up a 9 always carries — ask where else that happens.",
    ifNotSecure: "rnd-explain-down", ifSecure: "rnd-extend-range-dp",
  },
  {
    id: "rnd-zero-sf", level: "level3", tool: "sf", needs: ["sf2"], purpose: "diagnose",
    title: "Which zeros count?",
    visual: line(ITEM_LINES["rnd-zero-sf"]),
    question: ["Round $0.00472$ to $2$ significant figures."],
    options: [
      { text: "$0.0$", misconception: "Counts the leading zeros as significant figures" },
      { text: "$0.0047$", correct: true },
      { text: "$0.005$", misconception: "Rounds to 1 significant figure instead of 2" },
    ],
    answer: [
      "The first significant figure is the first non-zero digit: the $4$.",
      "The two significant figures are $4$ and $7$; the decider is $2$, so round down.",
      "$0.00472 \\to 0.0047$. Leading zeros are only place-holders.",
    ],
    teacherNote: "Colour the first non-zero digit. Ask: how many sig figs does 0.0047 have?",
    ifNotSecure: "rnd-digit-nearest", ifSecure: "rnd-extend-sfdp",
  },
  {
    id: "rnd-placeholder-sf", level: "level3", tool: "sf", needs: ["sf2"], purpose: "diagnose",
    title: "Keep the size",
    visual: line(ITEM_LINES["rnd-placeholder-sf"]),
    question: ["Round $4{,}726$ to $2$ significant figures."],
    options: [
      { text: "$47$", misconception: "Drops the digits instead of replacing them with zeros, so the size of the number is lost" },
      { text: "$4{,}700$", correct: true },
      { text: "$4{,}730$", misconception: "Rounds to 3 significant figures instead of 2" },
    ],
    answer: [
      "The two significant figures are $4$ and $7$; the decider is $2$, so round down.",
      "The remaining places are filled with zeros as place-holders: $4{,}726 \\to 4{,}700$.",
      "$47$ is a hundred times too small.",
    ],
    teacherNote: "Estimate: is the answer about 4,700 or about 47? The size must survive rounding.",
    ifNotSecure: "rnd-zero-sf", ifSecure: "rnd-extend-sfdp",
  },
  {
    id: "rnd-nine-dp", level: "level3", tool: "dp", needs: ["dp2"], purpose: "diagnose",
    title: "Carrying over",
    visual: line(ITEM_LINES["rnd-nine-dp"]),
    question: ["Round $0.0996$ to $2$ decimal places."],
    options: [
      { text: "$0.09$", misconception: "Cuts off after two decimal places without looking at the decider" },
      { text: "$0.10$", correct: true },
      { text: "$0.1$", misconception: "Drops the trailing zero, losing the accuracy" },
    ],
    answer: [
      "The rounding digit is $9$ and the decider is $9$, so round up.",
      "$0.09 + 0.01 = 0.10$: the carry moves into the tenths.",
      "The $0$ stays — it shows the answer is accurate to $2$ decimal places.",
    ],
    teacherNote: "Draw the line from 0.09 to 0.10 and place 0.0996 close to the top.",
    ifNotSecure: "rnd-nines", ifSecure: "rnd-extend-convince",
  },
  {
    id: "rnd-explain-double", level: "level3", tool: "dp", purpose: "explain",
    title: "Round twice?",
    speakers: [{ name: "Ben", says: ["Rounding $2.46$ to $1$ d.p. and then to the nearest whole number gives the same answer as rounding $2.46$ straight to the nearest whole number."] }],
    visual: line(ITEM_LINES["rnd-explain-double"]),
    question: ["Test Ben's claim. Is it true?"],
    answer: [
      "Ben's claim is false.",
      "Straight to the nearest whole number: $2.46 \\to 2$ (the decider is $4$).",
      "Via $1$ d.p.: $2.46 \\to 2.5 \\to 3$.",
      "The first rounding creates a new halfway case that was not there originally — always round from the original number.",
    ],
    teacherNote: "Ask which answer is right: 2.46 is nearer 2 than 3. This links to why rounding in stages (as Leo did) goes wrong.",
    ifNotSecure: "rnd-chain", ifSecure: "rnd-extend-range-dp",
  },
  {
    id: "rnd-explain-zoe", level: "level3", tool: "sf", needs: ["sf2"], purpose: "explain",
    title: "Explain this mistake",
    speakers: [{ name: "Priya", says: ["$0.0384$ to $2$ significant figures is $0.04$."] }],
    visual: line(ITEM_LINES["rnd-explain-zoe"]),
    question: ["How many significant figures has Priya used? What should the answer be?"],
    answer: [
      "$0.04$ has only $1$ significant figure: Priya rounded to $1$ s.f. instead of $2$.",
      "The first significant figure is the $3$, the second is $8$, and the decider is $4$, so round down.",
      "$0.0384 \\to 0.038$.",
    ],
    teacherNote: "Have them underline the first non-zero digit. Ask where the counting started.",
    ifNotSecure: "rnd-zero-sf", ifSecure: "rnd-extend-sfdp",
  },
  {
    id: "rnd-extend-range-dp", level: "level3", tool: "dp", purpose: "extend",
    title: "Smallest and largest",
    visual: line(ITEM_LINES["rnd-extend-range-dp"]),
    question: ["A number is rounded to $1$ decimal place and the answer is $2.4$.", "What is the smallest value it could be? Which value can it not quite reach?"],
    answer: [
      "Smallest: $2.35$ ($2.35$ rounds up to $2.4$).",
      "It cannot reach $2.45$ — that rounds up to $2.5$. So the number lies in $2.35 \\le x < 2.45$.",
      "The interval has width $0.1$ and $2.4$ is in the middle.",
    ],
    teacherNote: "This is the seed of error intervals — draw the interval on a number line.",
    ifNotSecure: "rnd-extend-range-50",
  },
  {
    id: "rnd-extend-sfdp", level: "level3", tool: "sf", purpose: "extend",
    title: "Always, sometimes, never",
    visual: line(ITEM_LINES["rnd-extend-sfdp"]),
    question: ["Rounding to $3$ significant figures is more accurate than rounding to $2$ decimal places.", "Always, sometimes or never? Try $0.00472$ and $472.3$."],
    answer: [
      "Sometimes.",
      "$0.00472$: $3$ s.f. is $0.00472$ but $2$ d.p. is $0.00$ — significant figures is more accurate.",
      "$472.3$: $3$ s.f. is $472$ but $2$ d.p. is $472.30$ — decimal places is more accurate.",
    ],
    teacherNote: "Draw out: the two measures count from different places.",
    ifNotSecure: "rnd-explain-zoe",
  },
  {
    id: "rnd-extend-convince", level: "level3", tool: "dp", needs: ["dp2"], purpose: "extend",
    title: "Convince me",
    visual: line(ITEM_LINES["rnd-extend-convince"]),
    question: ["Convince me that $2.995$ to $2$ decimal places is $3.00$ — not $2.99$ and not $3.0$."],
    answer: [
      "The rounding digit is the second $9$ and the decider is $5$, so round up.",
      "$2.99 + 0.01 = 3.00$.",
      "It must be written $3.00$ so the reader knows it is accurate to $2$ decimal places; $3.0$ only shows $1$.",
    ],
    teacherNote: "A good convincing argument uses the line from 2.99 to 3.00 and says 2.995 is exactly halfway.",
    ifNotSecure: "rnd-nine-dp",
  },

  // ───────────── Added so every sub-tool tab keeps diagnose, explain and extend at each level ─────────────
  {
    id: "rnd-dp1-who", level: "level1", tool: "dp", purpose: "diagnose",
    title: "Who is right?",
    speakers: [
      { name: "Leo", says: ["$3.46$ to $1$ decimal place is $3.4$ — I just stop after one digit."] },
      { name: "Priya", says: ["$3.46$ to $1$ decimal place is $3.5$ — the $6$ tells me to round up."] },
    ],
    visual: line(ITEM_LINES["rnd-dp1-who"]),
    question: ["Who is right?"],
    options: [
      { text: "Leo", misconception: "Cuts the number off after the rounding digit without looking at the digit after it" },
      { text: "Priya", correct: true },
      { text: "They are both right", misconception: "Thinks stopping early and rounding are the same thing" },
    ],
    answer: [
      "Priya is right: $3.46$ lies between $3.4$ and $3.5$.",
      "Halfway is $3.45$, and $3.46$ is past it, so it is closer to $3.5$.",
      "Leo's $3.4$ is a cut-off, not a rounding: it throws away the $6$ without letting it decide.",
    ],
    teacherNote: "Ask what Leo would write for $3.49$. The cut-off answer is only right when the next digit is small.",
    ifNotSecure: "rnd-dp1-explain", ifSecure: "rnd-dp1-always",
  },
  {
    id: "rnd-dp1-explain", level: "level1", tool: "dp", purpose: "explain",
    title: "Explain this mistake",
    speakers: [{ name: "Amara", says: ["$5.38$ to $1$ decimal place is $5.3$, because I chop off the $8$."] }],
    visual: line(ITEM_LINES["rnd-dp1-explain"]),
    question: ["Explain what Amara has done wrong. What should the answer be?"],
    answer: [
      "Amara chopped the $8$ off instead of using it to decide.",
      "$5.38$ is between $5.3$ and $5.4$. Halfway is $5.35$, and $5.38$ is past it.",
      "So $5.38$ is closer to $5.4$: $5.38 \\to 5.4$.",
    ],
    teacherNote: "Listen for 'she didn't look at the 8'. The digit after the rounding digit is the decider.",
  },
  {
    id: "rnd-dp1-always", level: "level1", tool: "dp", purpose: "extend",
    title: "Always, sometimes, never",
    visual: line(ITEM_LINES["rnd-dp1-always"]),
    question: ["A number rounded to $1$ decimal place is always written with exactly one digit after the decimal point.", "Always, sometimes or never? Think about $6.04$."],
    answer: [
      "Always.",
      "$6.04$ rounds to $6.0$, and the $0$ must stay: it shows the answer is accurate to $1$ decimal place.",
      "Writing $6$ would hide that the tenths digit was checked.",
    ],
    teacherNote: "Many drop the zero. Ask what the zero is telling the reader.",
  },
  {
    id: "rnd-dp-how-many", level: "level2", tool: "dp", purpose: "extend",
    title: "How many?",
    visual: line(ITEM_LINES["rnd-dp-how-many"]),
    question: ["How many numbers with $2$ decimal places round to $3.7$ when rounded to $1$ decimal place?", "List the smallest and the largest."],
    answer: [
      "Smallest: $3.65$ (halfway rounds up). Largest: $3.74$ ($3.75$ would round up to $3.8$).",
      "$3.65, 3.66, \\dots, 3.74$ — that is $10$ numbers.",
      "Every one of them is within $0.05$ of $3.7$.",
    ],
    teacherNote: "Compare with 'how many whole numbers round to 70?' — the same ten, scaled down.",
  },
  {
    id: "rnd-dp1-from-end", level: "level2", tool: "dp", purpose: "diagnose",
    title: "Round from the end?",
    question: ["What is $8.249$ to $1$ decimal place?"],
    visual: line(ITEM_LINES["rnd-dp1-from-end"]),
    options: [
      { text: "$8.2$", correct: true },
      { text: "$8.3$", misconception: "Rounds from the end: $8.249 \\to 8.25 \\to 8.3$, using each digit in turn" },
      { text: "$8.25$", misconception: "Stops at $2$ decimal places instead of $1$" },
    ],
    answer: [
      "Only the digit straight after the first decimal place decides: it is $4$, so the $2$ stays.",
      "$8.249$ is just below halfway ($8.25$), so it is closer to $8.2$.",
      "Rounding in stages ($8.249 \\to 8.25 \\to 8.3$) gives a different, wrong answer.",
    ],
    teacherNote: "Ask where $8.3$ came from. Round once, from the original number.",
  },
  {
    id: "rnd-dp1-zero", level: "level2", tool: "dp", purpose: "explain",
    title: "Explain this mistake",
    speakers: [{ name: "Leo", says: ["$27.46$ to $1$ decimal place is $27.40$ — I keep the $4$ and zero the $6$."] }],
    visual: line(ITEM_LINES["rnd-dp1-zero"]),
    question: ["Explain what Leo has done. What should the answer be?"],
    answer: [
      "Leo replaced the $6$ with a $0$ instead of using it to decide, and kept two decimal places.",
      "$27.46$ is between $27.4$ and $27.5$; halfway is $27.45$ and $27.46$ is past it.",
      "So $27.46 \\to 27.5$, with one decimal place.",
    ],
    teacherNote: "Ask how many decimal places $27.40$ has. The answer must show only one.",
  },
  {
    id: "rnd-dp1-carry", level: "level3", tool: "dp", purpose: "diagnose",
    title: "Carrying over",
    question: ["What is $0.96$ to $1$ decimal place?"],
    visual: line(ITEM_LINES["rnd-dp1-carry"]),
    options: [
      { text: "$1.0$", correct: true },
      { text: "$0.10$", misconception: "Adds $1$ to the $9$ and writes '10' in the tenths place without carrying" },
      { text: "$0.9$", misconception: "Cuts off after the rounding digit without looking at the decider" },
    ],
    answer: [
      "$0.96$ lies between $0.9$ and $1.0$; halfway is $0.95$ and $0.96$ is past it.",
      "So it rounds up to $1.0$: the $9$ becomes $10$ tenths, which carries into the units.",
      "The $0$ stays so the answer still shows $1$ decimal place.",
    ],
    teacherNote: "Ask what is ten tenths. The carry is just exchanging, as in column addition.",
  },
  {
    id: "rnd-sf1-carry", level: "level3", tool: "sf", purpose: "diagnose",
    title: "Carrying over",
    question: ["What is $9{,}640$ to $1$ significant figure?"],
    visual: line(ITEM_LINES["rnd-sf1-carry"]),
    options: [
      { text: "$10{,}000$", correct: true },
      { text: "$9{,}000$", misconception: "Keeps the first figure without letting the next one decide" },
      { text: "$1{,}000$", misconception: "Carries the $9$ but forgets the extra place the carry creates" },
    ],
    answer: [
      "$9{,}640$ lies between $9{,}000$ and $10{,}000$; halfway is $9{,}500$ and $9{,}640$ is past it.",
      "So it rounds up to $10{,}000$: the $9$ carries and the number gains a place.",
      "It still has $1$ significant figure: the $1$ followed by zeros.",
    ],
    teacherNote: "Ask how many digits the answer has compared with the original.",
  },
  {
    id: "rnd-sf1-zeros", level: "level3", tool: "sf", purpose: "explain",
    title: "Explain this mistake",
    speakers: [{ name: "Amara", says: ["$0.00472$ to $1$ significant figure is $0.0$ — the first digits are zeros so there is nothing to keep."] }],
    visual: line(ITEM_LINES["rnd-sf1-zeros"]),
    question: ["Explain what Amara has done wrong. What should the answer be?"],
    answer: [
      "Amara counted the leading zeros as figures. They are not significant: they only show the size.",
      "The first significant figure is the $4$; the $7$ after it decides, so it rounds up.",
      "So $0.00472 \\to 0.005$.",
    ],
    teacherNote: "Ask them to point to the first non-zero digit before they round.",
  },
  {
    id: "rnd-explain-middle", level: "level3", tool: "nearest", purpose: "explain",
    title: "Explain this mistake",
    speakers: [{ name: "Mei", says: ["$4{,}495$ to the nearest $10$ is $4{,}490$, because it is exactly in the middle so I stay down."] }],
    visual: line(ITEM_LINES["rnd-explain-middle"]),
    question: ["Explain Mei's reasoning. What is the rule for a number exactly in the middle?"],
    answer: [
      "A number exactly halfway between two marks rounds UP: $4{,}495 \\to 4{,}500$.",
      "Mei treated the middle as 'not far enough' to go up, but the convention is that halfway goes to the larger neighbour.",
      "Without a rule, everyone would choose differently, so rounding agrees to go up.",
    ],
    teacherNote: "Ask why a rule is needed at all. It is a convention, not a discovery.",
  },
  {
    id: "rnd-extend-range-10", level: "level3", tool: "nearest", purpose: "extend",
    title: "Smallest and largest",
    visual: line(ITEM_LINES["rnd-extend-range-10"]),
    question: ["A whole number is rounded to the nearest $10$ and the answer is $7{,}000$.", "What is the smallest it could be? What is the largest?"],
    answer: [
      "Smallest: $6{,}995$ (halfway rounds up).",
      "Largest: $7{,}004$ ($7{,}005$ would round up to $7{,}010$).",
      "Every whole number from $6{,}995$ to $7{,}004$ works: $10$ numbers.",
    ],
    teacherNote: "Compare with the nearest-100 version: the interval is always one rounding-unit wide, centred on the answer.",
  },
  {
    id: "rnd-sf1-which", level: "level1", tool: "sf", purpose: "diagnose",
    title: "One figure",
    question: ["What is $4{,}726$ to $1$ significant figure?"],
    visual: line(ITEM_LINES["rnd-sf1-which"]),
    options: [
      { text: "$5{,}000$", correct: true },
      { text: "$5$", misconception: "Gets the figure right but drops the zeros that keep its size" },
      { text: "$4{,}000$", misconception: "Keeps the first figure without letting the next one decide" },
    ],
    answer: [
      "$4{,}726$ lies between $4{,}000$ and $5{,}000$; halfway is $4{,}500$ and $4{,}726$ is past it.",
      "So it rounds to $5{,}000$.",
      "The three zeros are place-holders: without them the size is wrong.",
    ],
    teacherNote: "Ask what $5$ would mean as an answer. Place value is the point.",
    ifNotSecure: "rnd-sf1-explain", ifSecure: "rnd-sf1-always",
  },
  {
    id: "rnd-sf1-explain", level: "level1", tool: "sf", purpose: "explain",
    title: "Explain this mistake",
    speakers: [{ name: "Ruby", says: ["$326$ to $1$ significant figure is $3$, because $3$ is the first figure."] }],
    visual: line(ITEM_LINES["rnd-sf1-explain"]),
    question: ["Explain what Ruby has done wrong. What should the answer be?"],
    answer: [
      "Ruby found the figure but lost its size: $3$ is not close to $326$.",
      "$326$ is between $300$ and $400$; it is nearer $300$, so it rounds to $300$.",
      "The two zeros are place-holders.",
    ],
    teacherNote: "Ask how big the answer should be. A sense of size catches the missing zeros.",
  },
  {
    id: "rnd-sf1-always", level: "level1", tool: "sf", purpose: "extend",
    title: "Always, sometimes, never",
    visual: line(ITEM_LINES["rnd-sf1-always"]),
    question: ["A number rounded to $1$ significant figure has exactly one non-zero digit.", "Always, sometimes or never? Think about $96$."],
    answer: [
      "Always.",
      "$96 \\to 100$: the $9$ carries and becomes a $1$ followed by zeros.",
      "$4{,}726 \\to 5{,}000$ and $0.0372 \\to 0.04$ also have one non-zero digit.",
    ],
    teacherNote: "The carry case surprises: the answer has one digit but more places than the original's first figure.",
  },
  {
    id: "rnd-sf2-lead", level: "level2", tool: "sf", purpose: "diagnose",
    title: "Leading zeros",
    question: ["What is $0.0384$ to $2$ significant figures?"],
    visual: line(ITEM_LINES["rnd-sf2-lead"]),
    options: [
      { text: "$0.038$", correct: true },
      { text: "$0.04$", misconception: "Counts the zero after the decimal point as one of the two figures" },
      { text: "$0.039$", misconception: "Rounds up although the deciding digit, $4$, is small" },
    ],
    answer: [
      "The first significant figure is the first non-zero digit, $3$; the second is $8$.",
      "The next digit is $4$, which is less than $5$, so the $8$ stays: $0.038$.",
      "Leading zeros are never significant: they only show the size.",
    ],
    teacherNote: "Ask them to circle the first significant figure before choosing.",
    ifNotSecure: "rnd-sf2-explain", ifSecure: "rnd-sf2-range",
  },
  {
    id: "rnd-sf2-explain", level: "level2", tool: "sf", purpose: "explain",
    title: "Explain this mistake",
    speakers: [{ name: "Kofi", says: ["$8{,}462$ to $2$ significant figures is $85$."] }],
    visual: line(ITEM_LINES["rnd-sf2-explain"]),
    question: ["Explain what Kofi has done. What should the answer be?"],
    answer: [
      "Kofi rounded correctly to $85$ hundreds but left out the zeros that give its size.",
      "The $2$ significant figures are $8$ and $4$; the $6$ decides, so $84 \\to 85$ (hundreds).",
      "Written in full: $8{,}500$.",
    ],
    teacherNote: "Ask how many digits a number near 8,462 should have. The place-holders keep the size.",
  },
  {
    id: "rnd-sf2-range", level: "level2", tool: "sf", purpose: "extend",
    title: "Smallest and largest",
    visual: line(ITEM_LINES["rnd-sf2-range"]),
    question: ["A whole number is rounded to $2$ significant figures and the answer is $3{,}400$.", "What is the smallest it could be? What is the largest?"],
    answer: [
      "Smallest: $3{,}350$ (halfway rounds up).",
      "Largest: $3{,}449$ ($3{,}450$ would round up to $3{,}500$).",
      "The second significant figure is the hundreds, so the interval is $100$ wide, centred on $3{,}400$.",
    ],
    teacherNote: "Compare with rounding to the nearest 100: the same interval.",
  },
];
